### ISSUE TITLE
Update frontend libs

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#174]
Hello,

how to update frontend libs...
I start with new theme...

In my directory src/blocks/ i don't see block card-list for example....and in your repository I see that block

Thanks.

**Comment by IvanGrginovInf** [comment]
Hi @marijang, you can just copy the block (and all the components it's depending on, you can see this in the block's readme, for example: `node_modules/@eightshift/frontend-libs/blocks/init/src/blocks/custom/card-list/docs/readme.md`) from `node_modules/@eightshift/frontend-libs/blocks/init/src/blocks` to your own `theme_or_plugin_name/src/blocks` folder.

After that make sure to restart `npm start`.

Not all blocks are added to your project during setup as to not add unnecessary bloat to a new project (for example: most projects don't need a card list which is why we don't copy that block but **_almost_** all will require a heading / paragraph / image, etc).
