### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#182]
edited src/block/manifest and added
   "customBlocksName": "eightshift-block"

I copy columns and column block
changed column.php corrected namespace
changed columns.php corrected namespace

and then when i m in gutenberg the layout options.... not working for column.

Thanks

**Comment by marijang** [comment]
Ok i get it, when i copy from node modules then works...
Only i get error: rest_validate_from_value_shema....
. The "type" schema keyword for  can only be one of the built-in types: array, object, string, number, integer, boolean, and null. Please see 
wp-includes/functions.php on line 5229

**Comment by dingo-d** [comment]
This sounds like the `boolean` issue. We are fixing this in the upcoming version.

In your manifest wherever you have `bool` as a type you should change it to `boolean`.

**Comment by marijang** [comment]
Ok what happend....

1. I update npm
2. than there was problems with applicationBlocksEditor
3. find error with src icon in colum .... then i copy new version from node directory
4. ok error persists...
5. find that i need to change manually applicationBlocksEditor.js
6. Done error new wrappers dir need to be changed
7. Done error again oh there are variations niceeee still problem not gone
9. Copy and fix grid example and fix paths

uh painfull....
hm your idea is really great but there will be great if 

1. Some css classes are always the same there is no need for every component to set  heading font size.. etc..
    Maybe: master typography to be aplied

2. make some kind of repo where we can put our components 
    nice way to extend components.....

    for example i already make collapsable component 
    also i create others like grid and for example you put in group 5 cards I have options "grid view" where you can choose varation for first row and others. i m using that when i want to put 2 cards important and other in grid by 3

3. Update needs to be less painfull

**But really great job!!!!!**

**STILL i cant create new themes error is: missing wp boilerplate command** and i have empty custom block hm.....

** Suggestion
maybe create new directory for really custom blocks and your blocks need to go inside default block dir because i don't wanna extend yours.
or
npm command to. view all available blocks and i pick what i want for example
npm view packages
npm install columns 
npm theme fix prefix...

and if i change component i cant update .....




Still if I want to create new theme

**Comment by dingo-d** [comment]
> I update npm

That can be tricky as updating lib versions can break things. We're working on an update, hopefully, it will be out this or next week that has tons of things improved.

> Some css classes are always the same there is no need for every component to set heading font size.. etc..
Maybe: master typography to be applied

True, we'll be describing how you can set some things globally in the `manifest.json` from the `Blocks` folder that can be used in blocks and in scss.

We purposefully made everything modular, so if you need to use typography, you basically set it in one core place: for instance font family will go in the `assets` folder, but the font sizes and colors are handled by each component that uses it. Otherwise, it defaults to the font size defined globally.

> make some kind of repo where we can put our components
> nice way to extend components.....

Our boilerplate consists of 2 main libraries: 

https://github.com/infinum/eightshift-libs
https://github.com/infinum/eightshift-frontend-libs

The first one defines the PHP structure, the second one JS, blocks, and SCSS functionality.

We are adding more and more block examples to the frontend libs. Currently, we're working on an update where you'll be able to just copy components from libs into your project using WP-CLI. It's going to be AWESOME!

> Update needs to be less painful

Yeah, I agree. The problem is that GB editor is updated often and most of the time that breaks our implementation, so it's not easy to just update the libs as you'd do in other projects. That is why we take our time with updates and they are mostly major change releases, as there are breaking changes. And the versions are often locked together (meaning v2 of boilerplate cannot use v3 of libs etc.). 

It's a drawback, but I think after this last update we should have a more stable system (unless the core editor team at wp.org decides to completely rewrite their APIs).

Thanks for the feedback and we'll keep you updated when the new libs will come out. We improved on the documentation as well so it should be easy to follow and understand our motivation 🙂
