### ISSUE TITLE
Social-links

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#216]
When i include social links 
there is no svg icons because wp_kses_post how i can enable svg?

**Comment by iruzevic** [comment]
This is because all of the "unsafe" content is striped using wp_kses_post method.

You can run this command:
```
wp boilerplate create_escaped_view
```

and provide the filter to allow specific setpoints that can be find here:
https://github.com/infinum/eightshift-libs/blob/release/3.0.0/src/View/AbstractEscapedView.php

the filter to use is:
https://developer.wordpress.org/reference/functions/wp_kses_allowed_html/

tldr. just provide the filter and merge sets in an array for a callback

**Comment by marijang** [comment]
Danke:D
