### ISSUE TITLE
[BUG] Project setup not working with custom eightshiftLibsBranch props

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-frontend-libs#312]
I have tried to run this command:
`npx create-wp-project --eightshiftLibsBranch="release/3.1.0" --eightshiftFrontendLibsBranch="develop"`

after the setup frontend lib is installed with develop version but eightshift-libs are installed with the latests stabile one 3.0.6

**Comment by IvanGrginovInf** [comment]
@iruzevic seems this logic was never implemented for `libs`, only for `frontend-libs` (even tho both arguments exist), will add.

But this won't work with branches (the argument is not named properly) because it will try to install that specific version from NPM / Composer, not from github. Meaning you would need to use already released version on either.

Getting it to work with github would be tricky.

**Comment by IvanGrginovInf** [comment]
Actually I got it to work rather easily, will deploy a fix soon.

**Comment by IvanGrginovInf** [comment]
@iruzevic Deployed setup script version `2.0.11` which fixes this issue to npm, if you try it shortly after this has been done, please make sure to force use that version of the script (so you don't get the cached older version).
