### ISSUE TITLE
[BUG] Windows 10 issues

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-frontend-libs#345]
I'm going to list any issues I encounter while working on Windows and playing with the libs in this issue.

When I start the `npm run start` command I noticed these recomendadtions/warnings from scss (dart sass)

<img width="1920" alt="winissue1" src="https://user-images.githubusercontent.com/8638515/119228953-d3612b00-bb15-11eb-948f-1730730ea12e.PNG">

Also, the css variables are outputted out, so there must be some escaping happening in the column block

<img width="1920" alt="winissue2" src="https://user-images.githubusercontent.com/8638515/119228982-fb508e80-bb15-11eb-963c-70a564bfe7ed.PNG">

I'll keep adding anything I find out

## Your Environment

* PHP version: 7.4.19 
* Development environment: Docker inside WSL2
* Server type: Apache
* Operating System and version: Windows 10
* Frontend Libs version: develop

**Comment by goranalkovic-infinum** [comment]
None of these are related to Windows 😄 

The dart-sass messages are because they're deprecating `/` as a divison symbol, there's a couple of places in frontend libs where we should make changes to comply, but some of the messages are from normalize.css, which they will have to fix.

The styles getting escaped is due to not including the `EscapedView` class with an addition of allowing the `<style>` tag, something we should cover in the documentation (and maybe just include it by default).

**Comment by dingo-d** [comment]
Yeah, I just discovered them while testing on Windows so I opened it under Windows issue lol

The second one is because of the kses filter (I'll add a PR for this). I can do the first one in the same batch
