### ISSUE TITLE
Error in npm start fresh new theme

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-frontend-libs#635]
ERROR in ./node_modules/@eightshift/frontend-libs/scripts/editor/css-variables.js 307:9-38
Module not found: Error: Can't resolve 'crypto' in '/Applications/MAMP/htdocs/bjn/wp-content/themes/b4b/node_modules/@eightshift/frontend-libs/scripts/editor'

**Comment by dingo-d** [comment]
Hi! The current version is a bit broken, the release that fixes it should be out soon. In the meantime you can try to set up the project using

```bash
npx create-wp-project --eightshiftLibsBranch="develop" --eightshiftFrontendLibsBranch="develop" --eightshiftBoilerplateBranch='develop'
```

That should work, but since it's tied to the develop version, once the new version comes out we recommend you fix the dependencies to the latest version.

That is, you shouldn't use the develop versions on a production projects 🙈

**Comment by iruzevic** [comment]
this is fixed
