### ISSUE TITLE
Global manifest schema implies only hex values are supported in color declarations, which is not true

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-frontend-libs#672]
### Describe your bug

![Screenshot 2022-10-05 at 17 11 30](https://user-images.githubusercontent.com/1742806/194096243-993b0d4c-d8e5-4d7d-94be-0b6eb37827f6.png)

### Steps to Reproduce

If this is contained in the `globalVariables.colors` in the global blocks manifest, you'll get a warning from a JSON schema-supporting editor:
```
			{
				"name": "Black / 25%",
				"slug": "black-opacity-25",
				"color": "rgba(14, 3, 37, 0.25)"
			}
```

### Expected behavior

Using RGBA values is supported, so this shouldn't trigger a warning.

Support in color picker component:

![Screenshot 2022-10-05 at 17 17 46](https://user-images.githubusercontent.com/1742806/194097592-7518af70-48ef-4a80-b2a6-805f4f73bef4.png)

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

No

**Comment by goranalkovic-infinum** [comment]
While this is true, we discourage two things demonstrated here:
- colors in the `rgb` notation shouldn't be used because we're internally converting the hex code to RGB values so we can generate a `--global-colors-{colorName}-values` variable for each color, which brings us to point 2:
- transparent versions of existing colors shouldn't be in the manifest, it adds unnecessary clutter, the helper mentioned above can help you get to any transparent color with the recent `rgb()` notation (e.g. `rgb(var(--global-colors-{colorName}-values / {opacity})`)
